--- 
env: 
  UNITY_EMAIL: "${{ secrets.UNITY_EMAIL }}"
  UNITY_PASSWORD: "${{ secrets.UNITY_PASSWORD }}"
  UNITY_SERIAL: "${{ secrets.UNITY_SERIAL }}"
jobs: 
  buildWebGL: 
    name: "Build for WebGL 🖥️"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout code"
        uses: actions/checkout@v2
      - 
        name: "SSH key"
        uses: webfactory/ssh-agent@v0.5.2
        with: 
          ssh-private-key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - 
        name: Cache
        uses: actions/cache@v2
        with: 
          key: Library-WebGL
          path: Library
          restore-keys: Library-
      - 
        name: Build
        uses: game-ci/unity-builder@v2
        with: 
          targetPlatform: WebGL
          unityVersion: auto
          versioning: Semantic
      - 
        name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with: 
          name: build-HotHandsWebGL
          path: build/WebGL
    strategy: 
      fail-fast: false
  deployPage: 
    name: "Deploy to Github Pages 🚀"
    needs: buildWebGL
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout code"
        uses: actions/checkout@v2
      - 
        name: "Download artifact"
        uses: actions/download-artifact@v2
        with: 
          name: build-HotHandsWebGL
          path: build
      - 
        name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with: 
          branch: gh-pages
          folder: build/WebGL
name: "GitHub Page Build"
true: 
  workflow_dispatch: {}
